# Configuration File for Development (Updated)
server:
  port: 4000
  host: 0.0.0.0
  timeout: 10000
  debug: true
database:
  host: develop-db.example.com
  user: develop_admin
  password: secure_develop_pass
  max_connections: 50
  debug_queries: true
