name: Manual Backport Test
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to backport'
        required: true
        type: string

jobs:
  test-backport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger backport
        uses: korthout/backport-action@v3
        with:
          source_pr_number: ${{ github.event.inputs.pr_number }}
          target_branches: develop
          github_token: ${{ secrets.BOT_MERGE_TOKEN }}
          experimental: >
            {
              "conflict_resolution": "draft_commit_conflicts"
            }
